production:
  stage: deploy
  tags:
    - prod-runner
  script:
    - cd /var/www/divya-om
    - git reset --hard
    - git pull
    - yarn
    - yarn build
    - sudo service nginx restart
  only:
    - master
